### ISSUE TITLE
Replace the old school western emoticon by their unicode equivalent

### ISSUE THREAD

**Issue by PerfectCarl** [I-hate-farms/hippopogram#1]
Replace _old school_ [western emoticons](http://www.wikiwand.com/en/List_of_emoticons#Western) like `:-)` and `>:)` by their modern image equivalents

![sample](https://github.com/I-hate-farms/hippopogram/raw/master/doc/emoticons.png) 

List of supported emoticons: 
- ':-)', ':)', ':D', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)', '=)', ':}', ':^)', ':っ)'
- ':-D', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D', '=D', '=-3', '=3', 'B^D'
- ':-))'
- '>:[', ':-(', ':(', ':-c', ':c', ':-<',  ':っC', ':<', ':-[', ':[', ':{'
- ';('
- ':-||', ':@', '>:('
- ':'-(', ':'('
- ':'-)', ':')'
- 'D:<', 'D:', 'D8', 'D;', 'D=', 'DX', 'v.v', 'D-\':']
- '>:O', ':-O', ':O', ':-o', ':o', '8-0', 'O_O', 'o-o', 'O_o', 'o_O', 'o_o', 'O-O'
- ':_', ':^_', '( '}{' )'
- ';-)', ';)', '_-)', '_)', ';-]', ';]', ';D', ';^)', ':-,'
- '>:P', ':-P', ':P', 'X-P', 'x-p', ':-p', ':p', '=p', ':-Þ', ':Þ', ':þ', ':-þ', ':-b', ':b'
- '>:\', '>:/', ':-/', ':-.', ':\', '=/', '=\', ':L', '=L', ':S', '>.<'
- ':|', ':-|'
- ':$'

**Comment by PerfectCarl** [comment]
Implemented

**Comment by AnniMoham** [comment]
':-)', ':)', ':D', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)', '=)', ':}', ':^)', ':っ)'
